import eslint from '@eslint/js'
import eslintConfigPrettier from 'eslint-config-prettier'

export default [
    {
        ignores: [
            '**/*.*',

            '!shared/src/**/*.*',

            '!play/src/**/*.*',

            '!watch/src/**/*.*',

            '!preview/src/**/*.*',

            '!tutorial/src/**/*.*',
        ],
    },

    eslint.configs.recommended,

    {
        rules: {
            'no-restricted-properties': [
                'error',
                {
                    object: 'debug',
                    message: 'Debug calls should be removed from production.',
                },
            ],
        },
    },

    eslintConfigPrettier,

    {
        files: ['shared/src/**/*.*'],

        languageOptions: {
            globals: {
                Collection: false,
                Container: false,
                ContainerType: false,
                DataType: false,
                Dictionary: false,
                Mat: false,
                Quad: false,
                Range: false,
                Rect: false,
                Tuple: false,
                Vec: false,
                EffectClipId: false,
                ParticleEffectId: false,
                SkinSpriteId: false,
                LoopedEffectClipInstanceId: false,
                ParticleEffectInstanceId: false,
                ScheduledLoopedEffectClipInstanceId: false,
                native: false,
            },
        },
    },

    {
        files: ['play/src/**/*.*'],

        languageOptions: {
            globals: {
                Archetype: false,
                SpawnableArchetype: false,
                levelData: false,
                levelMemory: false,
                Collection: false,
                Container: false,
                ContainerType: false,
                DataType: false,
                Dictionary: false,
                Mat: false,
                Quad: false,
                Range: false,
                Rect: false,
                Tuple: false,
                Vec: false,
                defineArchetypes: false,
                defineBuckets: false,
                defineEffect: false,
                defineOptions: false,
                defineParticle: false,
                defineSkin: false,
                Callback: false,
                EntityState: false,
                HorizontalAlign: false,
                Judgment: false,
                EffectClipId: false,
                ParticleEffectId: false,
                SkinSpriteId: false,
                LoopedEffectClipInstanceId: false,
                ParticleEffectInstanceId: false,
                ScheduledLoopedEffectClipInstanceId: false,
                TouchId: false,
                audio: false,
                background: false,
                bpmChanges: false,
                compiler: false,
                debug: false,
                entityInfos: false,
                input: false,
                life: false,
                multiplayer: false,
                native: false,
                score: false,
                screen: false,
                time: false,
                timeScaleChanges: false,
                touches: false,
                ui: false,
            },
        },
    },

    {
        files: ['preview/src/**/*.*'],

        languageOptions: {
            globals: {
                Archetype: false,
                previewData: false,
                Collection: false,
                Container: false,
                ContainerType: false,
                DataType: false,
                Dictionary: false,
                Mat: false,
                Quad: false,
                Range: false,
                Rect: false,
                Tuple: false,
                Vec: false,
                defineArchetypes: false,
                defineOptions: false,
                defineSkin: false,
                Callback: false,
                HorizontalAlign: false,
                PrintColor: false,
                PrintFormat: false,
                Scroll: false,
                SkinSpriteId: false,
                bpmChanges: false,
                canvas: false,
                compiler: false,
                debug: false,
                entityInfos: false,
                native: false,
                screen: false,
                timeScaleChanges: false,
                ui: false,
            },
        },
    },

    {
        files: ['watch/src/**/*.*'],

        languageOptions: {
            globals: {
                Archetype: false,
                SpawnableArchetype: false,
                levelData: false,
                levelMemory: false,
                Collection: false,
                Container: false,
                ContainerType: false,
                DataType: false,
                Dictionary: false,
                Mat: false,
                Quad: false,
                Range: false,
                Rect: false,
                Tuple: false,
                Vec: false,
                defineArchetypes: false,
                defineBuckets: false,
                defineEffect: false,
                defineOptions: false,
                defineParticle: false,
                defineSkin: false,
                Callback: false,
                EntityState: false,
                HorizontalAlign: false,
                Judgment: false,
                EffectClipId: false,
                ParticleEffectId: false,
                SkinSpriteId: false,
                LoopedEffectClipInstanceId: false,
                ParticleEffectInstanceId: false,
                ScheduledLoopedEffectClipInstanceId: false,
                audio: false,
                background: false,
                bpmChanges: false,
                compiler: false,
                debug: false,
                entityInfos: false,
                input: false,
                life: false,
                native: false,
                replay: false,
                score: false,
                screen: false,
                time: false,
                timeScaleChanges: false,
                ui: false,
            },
        },
    },

    {
        files: ['tutorial/src/**/*.*'],

        languageOptions: {
            globals: {
                tutorialData: false,
                tutorialMemory: false,
                Collection: false,
                Container: false,
                ContainerType: false,
                DataType: false,
                Dictionary: false,
                Mat: false,
                Quad: false,
                Range: false,
                Rect: false,
                Tuple: false,
                Vec: false,
                defineEffect: false,
                defineInstruction: false,
                defineOptions: false,
                defineParticle: false,
                defineSkin: false,
                NavigationDirection: false,
                TutorialCallback: false,
                EffectClipId: false,
                InstructionIconId: false,
                InstructionTextId: false,
                ParticleEffectId: false,
                SkinSpriteId: false,
                LoopedEffectClipInstanceId: false,
                ParticleEffectInstanceId: false,
                ScheduledLoopedEffectClipInstanceId: false,
                audio: false,
                background: false,
                compiler: false,
                debug: false,
                native: false,
                navigation: false,
                screen: false,
                time: false,
                ui: false,
            },
        },
    },
]
