import { Text } from '@sonolus/core'
export const optionsDefinition = {
    speed: {
        name: Text.Speed,
        standard: true,
        advanced: true,
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    hidden: {
        name: Text.Hidden,
        standard: true,
        advanced: true,
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    noteSpeed: {
        name: Text.NoteSpeed,
        scope: 'Sekai',
        type: 'slider',
        def: 6,
        min: 1,
        max: 12,
        step: 0.01,
    },
    mirror: {
        name: Text.Mirror,
        type: 'toggle',
        def: 0,
    },
    version: {
        name: 'Version',
        description: 'Select version for effects and others',
        scope: 'Sekai',
        type: 'select',
        def: 0,
        values: ['v3', 'v1'],
    },
    customCombo: {
        name: 'Using Sekai Combo',
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    customJudgment: {
        name: 'Using Sekai Judgment',
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    ap: {
        name: 'AP Effect',
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    comboDistance: {
        name: 'Custom Combo Number Distance',
        scope: 'Sekai',
        advanced: true,
        type: 'slider',
        def: 0.25,
        min: -0.5,
        max: 0.5,
        step: 0.01,
    },
    fastLate: {
        name: 'Late/Fast/Flick',
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    auto: {
        name: 'Output Judgment As Auto In Watch Mode',
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    autoCombo: {
        name: 'Hide Combo In Watch Mode',
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    lightweight: {
        name: 'Using Lightweight Skin',
        scope: 'Sekai',
        type: 'toggle',
        def: 0,
    },
    sfxEnabled: {
        name: Text.Effect,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    autoSFX: {
        name: Text.EffectAuto,
        scope: 'Sekai',
        type: 'toggle',
        def: 0,
    },
    noteEffectEnabled: {
        name: Text.NoteEffect,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    noteEffectSize: {
        name: Text.NoteEffectSize,
        scope: 'Sekai',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    markerAnimation: {
        name: Text.MarkerAnimation,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    simLineEnabled: {
        name: Text.Simline,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    connectorAlpha: {
        name: Text.ConnectorAlpha,
        scope: 'Sekai',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    guideAlpha: {
        name: 'Guide Opacity',
        scope: 'Sekai',
        type: 'slider',
        def: 0.6,
        min: 0.1,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    connectorAnimation: {
        name: Text.ConnectorAnimation,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    laneEffectEnabled: {
        name: Text.LaneEffect,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    slotEffectEnabled: {
        name: Text.SlotEffect,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    slotEffectSize: {
        name: Text.SlotEffectSize,
        scope: 'Sekai',
        type: 'slider',
        def: 1,
        min: 0,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    optimize: {
        name: 'Performance Optimization(Not Working yet)',
        advanced: true,
        scope: 'SekaiRush',
        type: 'toggle',
        def: 0,
    },
    stageCover: {
        name: Text.StageCoverVertical,
        advanced: true,
        scope: 'Sekai',
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.01,
        unit: Text.PercentageUnit,
    },
    lockStageAspectRatio: {
        name: Text.StageAspectratioLock,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    hideUi: {
        name: 'Hide UI',
        scope: 'Sekai+',
        type: 'toggle',
        def: 0,
    },
    showLane: {
        name: Text.Stage,
        scope: 'Sekai+',
        type: 'toggle',
        def: 1,
    },
    previewVerticalScale: {
        name: Text.PreviewScaleVertical,
        scope: 'Sekai',
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    previewMeasure: {
        name: Text.PreviewMeasure,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    previewBeat: {
        name: Text.PreviewBeat,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    previewTime: {
        name: Text.PreviewTime,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    previewBpm: {
        name: Text.PreviewBpm,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
    previewTimeScale: {
        name: Text.PreviewTimescale,
        scope: 'Sekai',
        type: 'toggle',
        def: 1,
    },
}
